---
platform: linux

image_resource:
  type: docker-image
  source:
    repository: java
    tag: '8'

inputs:
  - name: source

run:
  path: source/ci/tasks/unit.sh
  args: [
    --input-dir, source
  ]
